https://mermaid.live/edit#pako:eNqNUktP3DAQ_ivWcFmkZJXEyW4wElJhe6jECW5tevDGEzZqYhs_VLar_e91HsBSKsRcPJ7vNVF8gFoJBAYPhusdub2rJAl17dtO_LjDR4_Wke1w-8kY-6I1ieMrcqtq3o2cxdhOjPNJ-wqO3BvV6w4dTvJKTiTrt1PiN6m9s_NQeVOjXdyPJxk2Ow8ybVSYzpxayaZ9WNyMxztUoEYpUNZtsNmcXN4xA_KyyxQbL-Or191P0_6HnCb9iw-MuuPWbrAJxIb7zpGm7Tp21owVWWfUL2RnlNK5j3-3wu1Ypp8u38jnpT8vfx4IbnfcGL5nJCf0rSkP_3EyFDk25fbjfchcEEGPpuetCO_lMBhW4HbYYwUstPOHVlDJY6B6LbjDr6J1ygBreGcxAu6dut_LGpgzHp9Jm5aHx9C_sDSXwA7wBIxm2XK1zpKiTJMiX5XrIoI9sCzNl1ma0LJMS1pc0HVxjOCPUsEiWRYpTYsyS5J8ldFkUAS_7yM4hB7_AnLe9pM
