https://mermaid.live/edit#pako:eNqNk9uO2jAQhl_F8t5kJUCQhMN6pVZt6EXVVVUtV-2yF8aZbCISO41tFQq8ex3bQACpWkfyYebzPzN2vMNMpIAJfmtonaOn5yVHpn3WRZm-PMNvDVKhVbt6JYR8qmvU739IKMvhG2yDhJZMl1QBYq0JrWF77wSOSIujJAe2tpbATh19JE9Oy_5oQAJXOz9-PDjKL1tk_xPkHiWiqktQ8DIXHF5voe9ij54Eo6UtxfldL_XKFbugPF2JjbOe2cD2PjvgZu814RLVMg_aDilxUZC12bJ9iu7gjjKn8F95rZX0RqEbBjJY2BG1d3JvttWNMFbPMMGz4i1I7HDjTaE2uQJnhZGZdxY3ZKckH7Y_ON9pN9atvRvl1tuRuz76s-C151qy63d5spJKOYfMoBnVpUJZUZbkLrOtJ1Uj1kDuoijy8_6fIlU5CevN48V2fwrv3340pFTmtGnolqAYRZei1DwJJ5jGkM1W_88H-YZ7uIKmokVqnt6uFVxilUMFS0zM1Be6xEt-MKiuU_PGvqSFEg0mGS0l9DDVSiy2nGGiGg1HaF5Q83dVJ6qmHJMd3mAyisaD2WwyDofRbDyNw7CHt631YTAZD-NoEg9H0WQaHnr4rxBGYGjocfgQx9OR-SbDaWTVfllnG_LwD2PZYaY
