https://mermaid.live/edit#pako:eNqNkl9vgjAUxb9KU18wQUJbEOiSJZvujcRkvpiJDxXqZAoltWQ643dfpbjMf9n61HN_p-feNt3DVGQcUvguWbUE8WtSAr3GyBqLWqYcHHGXUrrI1xz0eo9ggKyBKCotZbc14_tmfGUm983kyjyxHMc5N02mujQzfICa2ghZo_kHT9XJ2VJsKL5NiaHkNp0YejaAQSPTNLbivFz9jDoyzeJWkTM1-a3iRjyj6VNVzXSyqFVVq6Q0NF2zzWbIFyDjC1avFdCN17SzaJa9UVKsOO0QQtp97zPP1JLiavtwEdA82b9PnwoZ2yyZlGxHgQfIZaaZtU0N55nH_5jpeBrasOCyYHmm_9n-mJhAteQFTyDV2_aiCUzKg7bWVcYUf8lyJSSkStbchqxWYrwr05M2nmHO9K8tTsWKlZDu4RZS5LlO5Ie-h8LARSjANtxBit3IiYgX-SgIMcZ9v3-w4ZcQOsB1wgBHhHgk8F2Mo6BJe2vYMfzwDQTc75c
