https://mermaid.live/edit#pako:eNqNUl9vmzAQ_yon92WTCAo4IeBVkzalD5PyMKUPqwY8uPgoqAYjY9pkUb57bUJLK03T_OLz_f747uwTKZRAwsiD5l0Fu33WAvTD_eW4xSeUqkMNkndGdQ4sZI2tSb8PtRRglJI5Y4x3IyZVwWXBiwrTTzsXw3j4nMP1wq6vk9hRsRVZO_vBYrG_-fbzhyOVXDcOcXu6x0YZBDxgMZhatdCjfqoLzK1ipx5ujUbewKSc7Z3WXurb5LPSj6iD9Ne45-_QNzD8CzhL71Lf93MAB05mIzw1OlU4dTqTwuu5pxF873A3O8Alf4ldTfMUwY3oMiTe91ssQWDJB2mgrKVkV-W4vN5o9YjsilI6xYvnWpiKhd3hywd5p1WBff__8teE4H3FteZHBiugH03t40-GYoVlfP_vemy7QDzSoG54LezPOzmzjJgKG8wIs-HUZEay9mypQye4wRtRG6UJK7ns0SN8MOr22BaEGT3gK2lbc_tzmzdWx1vCTuRAWBgl_jqIkzhIKF0ndLP2yJGwYBX6y80mTqIgiINotYzOHvmjlLUI_CWNQho61TIJR7PfI-JuPL8AVIcNlA
